services:
  firebase-emulator:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    container_name: kanban-firebase-emulator
    ports:
      - "4000:4000" # Emulator Suite UI
      - "9099:9099" # Authentication Emulator
      - "8080:8080" # Firestore Emulator
    volumes:
      - ./firebase.json:/app/firebase.json:ro
      - ./.firebaserc:/app/.firebaserc:ro
      - ./firestore.rules:/app/firestore.rules:ro
